sudo: required

language: go

services:
  - docker

go:
  - 1.11.x
  - 1.12.x

os:
  - linux

before_install:
  - go get -v github.com/mattn/goveralls

install:
  - make setup

script:
  - make build
  - make test-race
  - make check
  - make bench-race
  - make coveralls

after_success:
  - if [ "$TRAVIS_OS_NAME" == "linux" -a ! -z "$TRAVIS_TAG" ]; then
    echo "Executing release on tag build $TRAVIS_TAG";
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    make release;
    else
    echo "Not executing release on non-tag build";
    fi
